# -*- coding: utf-8 -*-
"""NeuralNetworkGate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LBSL2ULvhK5avTgUFnNxAmuww57L-rBK
"""

import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def cross_entropy(y_true, y_pred):
    return -np.sum((y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)))

